# Generated by Django 6.0 on 2026-01-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_songs_account_songs_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='unique_id',
        ),
    ]
