# Generated by Django 6.0 on 2026-01-11 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_songs_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
