# Generated by Django 6.0 on 2026-02-12 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_songs_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='audio_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='songs',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='songs',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songs',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='songs',
            name='total_listen_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='songs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='track',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
