# Generated by Django 6.0 on 2026-02-12 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_songs_audio_features_songs_genre_songs_play_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
    ]
