# Generated by Django 6.0 on 2026-01-11 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0002_remove_songs_account_songs_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(default=0)),
                ('authorview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorview', to=settings.AUTH_USER_MODEL)),
                ('postview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postview', to='music.songs')),
            ],
        ),
    ]
