# Generated by Django 6.0 on 2026-01-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='views_count1',
            field=models.IntegerField(default=0),
        ),
    ]
