# Generated by Django 6.0 on 2026-01-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songsview', '0002_view_views_count1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='views_count1',
        ),
    ]
