# Generated by Django 6.0 on 2025-12-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
